name: Debug

on:
  workflow_dispatch: { }

jobs:
  primary:
    name: 'Primary'
    runs-on: ubuntu-latest
    steps:
      - uses: catchpoint/workflow-telemetry-action@v1
        with:
          comment_on_pr: false
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
      # https://github.com/docker/metadata-action
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: fzyzcjy/jupyter-docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fzyzcjy
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: mxschmitt/action-tmate@v3
